<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ApplicationIcon>Assets\PmeSync.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\PmeSync.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
